name: 6015
on: push

jobs:
 job-linux:
   runs-on: ubuntu-latest
   steps:
     - run: echo "Linux OK"
     
 job-windows:
   runs-on: windows-latest
   steps:
     - run: echo "Windows OK"
 
 job-macos:
   runs-on: macos-latest
   steps:
     - run: echo "MacOS OK"
     
     
